swagger: "2.0"
info:
  title: Storage Service
  description: "Service-facing REST API for storage of resources on the cloud."
  version: 2.0.0
basePath: /
produces:
  -  application/vnd.blinkbox.books.ingestion.storageservice.v2+json
paths:
  /mappings:
    get:
      summary: Lookup virtual URI mapping
      tags:
        - Mapping
      responses:
        200:
          description: "Mapping"
          schema:
            $ref: '#/definitions/MappingFile'

  /resources/{token}:
    get:
      summary: Information about a specific resource
      description: "Get the details about the particular resource and where it is stored."
      tags:
        - Mapping
      parameters:
        - name: token
          in: path
          type: string
          required: true
          description: "The virtual URL being looked up"
      responses:
        200:
          description: "Details of this resource (given that at least 1 provider has this data)"
          schema:
            $ref: '#/definitions/ProviderStatusResponse'
        404:
          description: "The specified resource cannot be found on any of the associated providers."
          examples:
            application/vnd.blinkbox.books.ingestion.storageservice.v2+json: |
              {
                "code": "NotFound",
                "providers": ["azure-alpha", "gluster"]
              }

  /resources:
    post:
      summary: Upload a new resource
      description: "Upload a resource to the storage service."
      consumes:
      - multipart/form-data
      parameters:
        - name: label
          in: formData
          type: string
          description: "The grouping the client wishes to post the resource into"
          required: true
        - name: data
          in : formData
          type: file
          description: "The blob of the resource"
          required: true
      tags:
        - Mapping
      responses:
        202:
          description: "Resource received and upload request accepted. Storage on remote systems will continue in the background."
          schema:
            $ref: '#/definitions/ProviderStatusResponse'
        400:
          examples:
            application/vnd.blinkbox.books.ingestion.storageservice.v2+json: |
              {
                "code": "InvalidParameters"
              }
          description: "Missing or invalid parameters"

definitions:
  MappingFile:
    description: "List of templates that describe how to create a url from a token. Object keys are regular expressions which should match some tokens. Named groups should be used so that components of the token can be inserted into the URLs contained"
    type: array
    items:
      description: "An object describing a label and how to map tokens of that label's type to URLs"
      type: object
      required:
        - label
        - extractor
        - providers
      additionalProperties: false
      properties:
        label:
          description: "The label described by this definition"
          type: string
        extractor:
          description: "A regular expression using named capture groups (PCRE 7.2 format: `(?<name>.+)`) which will match tokens made for this label"
          type: string
        providers:
          description: "List of providers which are used for this label. Object key is the provider name"
          type: object
          additionalProperties:
            description: "A URL with templated sections in sprintf form eg. `https://storage.example.com/bucket/%{variableName}` where `variableName` is a named group catured in the regular expression key above."
            type: string

  ProviderStatusResponse:
    description: "progress status of a resource's storage"
    required:
      - token
      - label
      - providers
    additionalProperties: false
    properties:
      token:
        description: "a token which represents mapped resources in the cloud"
        type: string
      label:
        description: "allows you to group assets, define some attributes of how they are stored"
        type: string
      providers:
        type: object
        description: "a map of storage requests ->complete boolean"
        additionalProperties:
          description: "Details of the resource as stored in the various providers"
          type: object
          required:
            - available
          additionalProperties: false
          properties:
            available:
              description: "Can the resource be found at this location"?
              type: boolean
            eta:
              description: "Number of seconds until upload is expected to complete, absent if complete or not started"
              type: number
              minimum: 0
            percentComplete:
              description: "Upload complete percentage as fraction of 1, absent if complete or not started"
              type: number
              minimum: 0
              maximum: 1
