swagger: 2
info:
  title: QuarterMaster Storage - Public API
  description: Consumer facing REST API for storage of resources on the cloud.
  version: 1.0.0
# Service configuration
host: www.blinkbox.com
schemes:
  - http
  - https
basePath: /
produces:
  - application/json
# Service end-points
paths:
  /mapping:
    get:
      summary: Lookup mapping, only available internally
      tags:
        - Mapping
      responses:
        200:
          description: Mapping
          schema:
            $ref: MappingFile
        401:
          description: Not authenticated
        404:
          description: No mapping file found
    post:
      summary: set the new mapping file
      description: Sets the latest mapping file, this has a side effect of broadcasting the mapping file update over rabbitmq
      parameters:
        - name: mapping
          in: body
          description: Data
          required: true
          schema:
            $ref: MappingFile
      tags:
        - Mapping
      responses:
        200:
          description: Mapping updated successfully
          schema:
            $ref: MappingFile
        401:
          description: Not authenticated
        404:
          description: Unknown or invalid storage request
  /qm/resources/{hash}:
    get:
      summary: get a resource uri
      description: query the uri of a resource
      parameters:
        - name: mapping
          in: path
          description: Data
          required: true
          type: string
      tags:
        - Mapping
      responses:
        200:
          description: resource added successfully
          schema:
            $ref: ProviderStatusResponse
        401:
          description: Not authenticated
        404:
          description: Unknown or invalid resource
  /qm/resources:
    post:
      summary: add new resource
      description: add a new resource to quartermaster
      parameters:
        - name: mapping
          in: body
          description: a request to the quartermaster to store data
          required: true
          schema:
            $ref: ProviderStorageRequest
      tags:
        - Mapping
      responses:
        200:
          description: resource added successfully
          schema:
            $ref: ProviderStatusResponse
        401:
          description: Not authenticated
        404:
          description: Unknown or invalid request
definitions:
  StorageTemplate:
      title: For a named storage:A structure which describes how to apply a set of tokens to its template in order to generate a url for a resource
      properties:
        storage:
          type: string
          title: one the enumerated names available storages
        template:
          type: string
          title: a string containing placeholders where tokens are added to generate a url for a resource
  MappingFile:
    title: List of templates that describe how to create a url from the uri passed back from quarter master
    properties:
      extractorPattern:
        type: string
        title: a regex containing groups that capture tokens to apply to templates to produce urls for each of the enumerated storages
      templates:
        type: array
        title: an Map of Templates that describes how to create a url from the tokens extracted for a given storagename
        schema:
          $ref: StorageTemplate

  ProviderStatus:
    title: progress status of a resource's storage, an empty finish date suggest incomplete or broken status
    type: object
    properties:
      available:
        type:  boolean
        title: can this file be found at this location
      eta:
        type: number
        title: number of seconds until upload is expected to complete, absent if complete
      percentComplete: 
        type: number
        title: upload complete percentage as fraction of 1, absent if complete
      
  ProviderStorageRequest:
    title: a http form post/put request to quarter master containing the following fields
    properties:
      tagslist:
        type: string
        title: a list of tags for the blob
      payload:
        type: blob
        title: http post file upload
  ProviderStatusResponse:
    title: progress status of a resource's storage
    properties:
      token:
        type: string
        title: a token which represents mapped resources in the cloud
      providers:
        type: object
        title: a map on of storage requests ->complete boolean
        additionalProperties: 
          $ref: ProviderStatus
          title: the key is the name of the provider and the value represents the status of the provider
